# cleaning the data and turning relevant fields into factors
```{r}
library(e1071)
library(ROCR)
options(repos = c(CRAN = "https://cloud.r-project.org/"))
set.seed(1)

creditData=na.omit(read.csv ("credit_risk_dataset.csv", header = TRUE))
num_rows = dim(creditData)[1]
creditData$person_home_ownership <- factor(creditData$person_home_ownership)
creditData$loan_intent <- factor(creditData$loan_intent)
creditData$loan_grade <- factor(creditData$loan_grade)
creditData$cb_person_default_on_file <- factor(creditData$cb_person_default_on_file)

creditData$cb_person_default_on_file <- ifelse(creditData$cb_person_default_on_file == "Y", 1, 0)
print(head(creditData))
```

```{r}
library(dplyr)

home_ownership_types <- creditData %>% 
  count(person_home_ownership)

loan_intent <- creditData %>% 
  count(loan_intent)

loan_grade <- creditData %>% 
  count(loan_grade)

cb_person_default_on_file <- creditData %>% 
  count(cb_person_default_on_file)

## KNN 

## loan status is Y 
summary (creditData$person_home_ownership)

library(dummy)

# creating dummy variables
temp_ownership <- data.frame(person_home_ownership = creditData$person_home_ownership)
creditData <- cbind(creditData, dummy(temp_ownership))
creditData <- subset(creditData, select = -person_home_ownership)

temp_intent <- data.frame(intent = creditData$loan_intent)
creditData <- cbind(creditData, dummy(temp_intent))
creditData <- subset(creditData, select = -loan_intent)

temp_grade <- data.frame(grade = creditData$loan_grade)
creditData <- cbind(creditData, dummy(temp_grade))
creditData <- subset(creditData, select = -loan_grade)

creditData <- as.data.frame(sapply(creditData, function(x) as.numeric(as.character(x))))
creditData <- creditData

# normalizing the data
creditData$person_age = (creditData$person_age-mean(creditData$person_age))/sd(creditData$person_age)
creditData$person_income = (creditData$person_income - mean(creditData$person_income))/sd(creditData$person_income)
creditData$person_emp_length = (creditData$person_emp_length - mean(creditData$person_emp_length))/sd(creditData$person_emp_length)
creditData$loan_amnt = (creditData$loan_amnt - mean(creditData$loan_amnt))/sd(creditData$loan_amnt)
creditData$loan_int_rate = (creditData$loan_int_rate - mean(creditData$loan_int_rate))/sd(creditData$loan_int_rate)
creditData$cb_person_cred_hist_length = (creditData$cb_person_cred_hist_length - mean(creditData$cb_person_cred_hist_length))/sd(creditData$cb_person_cred_hist_length)
```
# split train and test sets and train the model on the training set
```{r}
training <- sample(1:num_rows, 0.8 * num_rows, replace=FALSE)
trainingSet <- subset(creditData[training, ]) 
testing <- setdiff(1:num_rows,training) 
testingSet <- subset(creditData[testing, ])

trainingSet$loan_status <- as.factor(trainingSet$loan_status)
testingSet$loan_status <- as.factor(testingSet$loan_status)

svmModel <- svm(loan_status ~., data = trainingSet, kernel = "linear", cost = 20, probability = TRUE)
print(svmModel)
```

# test the model on the testing set and get its acccuracy
```{r}
num_samples = dim(testingSet)[1]

predictLabels <-  predict(svmModel, testingSet, probability = TRUE)
predProbs <- attr(predictLabels, "probabilities")[,1]
error = sum(predictLabels!=testingSet$loan_status)
mis_rate=error/num_samples
accuracy = 1 - mis_rate
print(accuracy)
```
# Generate the confusion matrix
```{r}
library(caret)
library(ggplot2)
library(lattice)
conf_matrix <- confusionMatrix(as.factor(predictLabels), as.factor(testingSet$loan_status), positive = "1")
print(conf_matrix)
```
# Plot ROC and determine AUC
```{r}
pred = prediction(predProbs, testingSet$loan_status)
pred_svm = pred
roc_obj = performance(pred, measure = "tpr", x.measure = "fpr")
auc_obj = performance(pred, measure = "auc")
plot(roc_obj, main = paste("Area under the curve:", round(auc_obj@y.values[[1]], 2)))
```

